### ISSUE TITLE
[Feature Request]: Hide or censor IP-address in messages for players without permission

### ISSUE THREAD

**Issue by MCMDEV** [A248/LibertyBans#101]
### I have confirmed that ...

- [X] There is no duplicate feature request.

### Description

I would like to see a feature added where IP-addresses in punishment messages, records and alt detection are hidden or censored from players without a required permission.
This feature is useful if you want moderators to handle alt detection and IP-bans without letting them see the full IP-address of the player (for privacy and legal reasons).

**Comment by pwnker** [comment]
Yeah I would love to see this added too.

**Comment by cayoten** [comment]
Yes please! I'd love to see this in my community for my own & my members' safety.
