### ISSUE TITLE
Feature to enable permissions to bypass bans on join, mutes on chat, etc.

### ISSUE THREAD

**Issue by A248** [A248/LibertyBans#106]
When the player joins, check them for a permission to bypass bans applying to them.

The functionality of the permission should be behind a configuration flag.

**Comment by ahdg6** [comment]
It would be awesome to see more punishment types adding to this feature, like mute.
Then I can use LuckPerms Contexts System to manage punishment easily and it will introduce unlimited possible.

**Comment by A248** [comment]
We can't make a feature to bypass bans on join for all platforms we support. So, if we added a bypass permission for bans on join, it could only work on Velocity.

* On Bukkit, the `AsyncPlayerPreLoginEvent` does not allow permission checks.
* On BungeeCord, the `LoginEvent` does not allow permission checks.

**Comment by Folas1337** [comment]
> We can't make a feature to bypass bans on join for all platforms we support. So, if we added a bypass permission for bans on join, it could only work on Velocity.
> 
> * On Bukkit, the `AsyncPlayerPreLoginEvent` does not allow permission checks.
> * On BungeeCord, the `LoginEvent` does not allow permission checks.

Then may I ask how exactly AdvancedBan does it?
Personally support on Velocity would be enough for me but I guess not for everyone and documenting that it's just available on Velocity is also probably irritating and only sparks more conversations...

Still hoping it's coming at some point 🙏

**Comment by A248** [comment]
@Folas1337 AdvancedBan doesn't do it. To be precise: AdvancedBan does not have a feature where users with a certain permission can bypass bans.

AdvancedBan *does* have a different feature, called exempt permissions. If a user has an exempt permission, that user cannot be banned.

This issue is about a permission to bypass an existing ban, not a permission to prevent becoming banned. If you want exempt permissions, please open a new feature request.

**Comment by A248** [comment]
This issue will probably be closed in favor of an exemption feature: #131 . The reason is two-fold:
* This feature -- bypass permissions -- was originally requested in lieu of the other feature -- exempt permissions. As such, implementing exempt permissions would probably satisfy most users who want bypass permissions.
* Moreover, as noted above, this feature -- bypass permissions -- is limited by the inability to check permissions at login. Accordingly, we probably wouldn't be able to implement this feature anyway.

I'll close this issue soon unless someone has good reason to keep it open.
