### ISSUE TITLE
[Feature Request]: Non-Case-Sensitive tab completer

### ISSUE THREAD

**Issue by BlueTree242** [A248/LibertyBans#111]
### I have confirmed that ...

- [X] There is no duplicate feature request.

### Description

When you use any libertybans command, and enter first letter of player name, and it is uppercased it doesn't continue tab completing, not sure if this is a bug or a feature request but whatever

**Comment by KoxSosen** [comment]
I can't reproduce this. Could you please try reproducing without any plugins?
![image](https://user-images.githubusercontent.com/67807644/147882355-94263964-5b49-49c2-bcc8-294382004413.png)

**Comment by BlueTree242** [comment]
> I can't reproduce this. Could you please try reproducing it without any plugins? ![image](https://user-images.githubusercontent.com/67807644/147882355-94263964-5b49-49c2-bcc8-294382004413.png)

(i am aware of every plugin that interact with tab completer, also this doesn't happen on other plugins) it looks like you are try didn't get what i mean, type lowercased `k` and then you will reproduce it

**Comment by KoxSosen** [comment]
You are correct, sorry. The lower cased `k` doesn't tab-complete.

**Comment by BlueTree242** [comment]
exactly, this is the issue

**Comment by BlueTree242** [comment]
can you tell me which class manages that i wanna contribute 😅

**Comment by A248** [comment]
CommandsCore and StandardTabCompletion, in `bans-core`, handle general, non-command-specific tab completion.

**Comment by BlueTree242** [comment]
thanks, i found the exact part that does it i will just build it to make sure my changes are working (so i dont PR something that isnt working)

**Comment by A248** [comment]
It would be doubly appreciated if you wrote a unit test for this functionality.
