### ISSUE TITLE
[Feature Request]: Option to make Alt Detection appear for banned players

### ISSUE THREAD

**Issue by Boy0000** [A248/LibertyBans#116]
### I have confirmed that ...

- [X] There is no duplicate feature request.

### Description

Right now the alt account alert pops up every time someone logs on.
I wish there was an option to only have it show when someone joins on an alt only when they are banned, not afterwards.
/alts would naturally still show when being used but would be nice to make it a bit more useful.

Then when it comes up, you know someone is banevading iguess

**Comment by A248** [comment]
See the config option `show-which-alts`. I believe that is the feature you are looking for.

**Comment by Boy0000** [comment]
![image](https://user-images.githubusercontent.com/62521371/148866283-e5c819a5-a836-403b-ad3d-c02718c2a4c6.png)
its set to show all banned or muted, but it isnt a check on current status but history iguess?

**Comment by A248** [comment]
It counts only active/current bans. I've tested this myself and it should work correctly for you.

Did you remember to reload the configuration?

**Comment by A248** [comment]
Please re-open this issue or visit the support discord if the feature still does not work for you
