### ISSUE TITLE
[Feature Request]: /removeban <banID>

### ISSUE THREAD

**Issue by accLarson** [A248/LibertyBans#119]
### I have confirmed that ...

- [X] There is no duplicate feature request.

### Description

Implement a command which removes a ban from the database record.
`/removeban <banID>` or
`/deleteban <banID>` or
`/purgeban <banID>`
Something along those lines.

When a ban is given with an error or by mistake, a simple `/unban <player>` solves the issue immediately but does not solve the issue for the records displays with` /history <player>`.

`/unban <player>` still has its place as a way to unban a player early from their ban however I feel a new command should be implemented to delete ban records from the database. 

On my server, we use a players ban history to gauge the length of ban the player will receive. 
"_1st ban: 1-30 days  |  2nd ban: 20-perm  |  3rd+ ban: perm_"  - I include this in the header for `/history <player>` for staff convenience. 
Checking history becomes quite tedious when staff aren't sure if the records in `/history <player>` are valid or were mistakes which were corrected. It can be verified by checking the dates they were given however that becomes very laborious.

**Comment by A248** [comment]
I hope to complete this feature, for dramatic effect, exactly a year from its request; likewise, #157 exactly six months from its request.

**Comment by A248** [comment]
Implemented as `/libertybans expunge`. Aliases are configurable as with any other LibertyBans command.
