### ISSUE TITLE
[Feature Request]: Allow for a preset list of common punishment reasons to shorten commands

### ISSUE THREAD

**Issue by rymiel** [A248/LibertyBans#124]
### I have confirmed that ...

- [X] There is no duplicate feature request.

### Description

A lot of punishments tend to fall into common patterns for their reasoning. It would be nice to be able to shorten them when executing commands, allowing for faster and easier punishment execution, with fewer mistakes.

BanManager accomplishes this by substituting special strings which have a `#` in front.

Alternatively, a preset list of reasons which will be tab-completed when typing the reason field of a punishment command.

I have also considered doing this with an external plugin through the API, however I cannot modify drafted punishments as they are fired through `PunishEvent`s, only cancel and re-fire, which breaks UX for commands

**Comment by A248** [comment]
Although this issue relates somewhat to #180 , this one is purely related to reason specification without any bearing on time or type calculation. I am keeping both open as a reminder to implement multiple varieties of the feature.
