### ISSUE TITLE
[Feature Request]: Layouts

### ISSUE THREAD

**Issue by Deeptanil** [A248/LibertyBans#127]
### I have confirmed that ...

- [X] There is no duplicate feature request.

### Description

Layouts, literally copied idea from advanced ban. I would use this plugin but just am not since layouts is such a huge part of my server and how i run the server.

More about it from advanced ban:
```
Layout.yml
Messages:
Here you can define predefined reasons which can be used for (temp-)banning/muting/warning & kicking.
You can use them by just typing @Layout-NAME instead of the reason. So you can have different layouts with different information for different reasons.
And once you have defined them you do not have to type the whole reason.

Time:
Here you can define timelayouts which can be used for temporary-punishments.
You can use them by just typing #LAYOUT-NAME instead of the duration. The time increases every time a player gets punished with the same layout.
```

Just mess around with ab if you do not understand it!

**Comment by A248** [comment]
Are you sure this is not the same feature request as #124 ?

Under that feature request, predefined reasons can be used in place of writing out the full reason. For example, "/ban Player1 #hacking"
