### ISSUE TITLE
[Feature Request]: warn system

### ISSUE THREAD

**Issue by llt12213** [A248/LibertyBans#137]
### I have confirmed that ...

- [X] There is no duplicate feature request.

### Description

pls add a feature for warning and ban,
for example 
xxx is hacking and anticheat warned him,when xxx gets 10 warnings ,i want the server auto-excute /ban xxx 30d or others

(litebans has this feature,and libertybans is a promising plugin

**Comment by ahdg6** [comment]
Maybe Duplicate with #62

**Comment by llt12213** [comment]
same as #62
