### ISSUE TITLE
[Feature Request]: Do not display IP ban

### ISSUE THREAD

**Issue by SrBedrock** [A248/LibertyBans#141]
### I have confirmed that ...

- [X] There is no duplicate feature request.

### Description

Create permission to view IP ban notifications.

Example:
- `libertybans.banip.do.notify`
- `libertybans.banip.do.notifysilent`
- `libertybans.banip.undo.notify`
- `libertybans.banip.undo.notifysilent`

**Comment by A248** [comment]
What are you trying to accomplish? If all you want to do is hide IP addresses, you may want #101 . The silent feature (`-s`) may also help here.

In the LibertyBans model, we don't have the concept of an IP-ban except as a ban applying to an IP address. That is, there are bans, and bans can apply to either 1.) UUIDs or 2.) IP addresses. As such, it is very unlikely that this exact feature request will be implemented.

**Comment by SrBedrock** [comment]
> What are you trying to accomplish? If all you want to do is hide IP addresses, you may want https://github.com/A248/LibertyBans/issues/101 .


I was referring to the message in messages.yml (`additions.bans.success.notification`) that is sent in chat to all players who have `libertybans.banip.do.notify` permission


> The silent feature (-s) may also help here.

It's understandable, I think that all the staff at some point will forget to use `-s` as an argument in some punishment and will end up leaking a player's sensitive data, hence the idea of permissions.
