### ISSUE TITLE
Support: Mute permissions

### ISSUE THREAD

**Issue by sebastiaannnn** [A248/LibertyBans#147]
### LibertyBans Version

1.0.1

### I have confirmed that ...

- [X] LibertyBans is up to date
- [X] No similar issue has been reported

### Platform

Velocity

### Description

Hey i have given my staff mute perms yet they can't mute ppl..
![image](https://user-images.githubusercontent.com/68129758/161817924-ffca732c-6c03-46d1-8d95-306ee23b1d78.png)

**Comment by 4drian3d** [comment]
As it says in the documentation https://docs.libertybans.org/#/Permissions , you must first give `libertybans.commands` permission, which you don't seem to have given

**Comment by sebastiaannnn** [comment]
I think i have, /ban etc does work!

**Comment by A248** [comment]
I looked at the permissions shown in the screenshot you posted. Most of those permissions do not exist in LibertyBans 1.0.1.

The correct list of permissions is on the wiki page which is linked above.

(You may also want to consider joining either IRC or Discord for support)

**Comment by KoxSosen** [comment]
Closing, resolved in support channels.
