### ISSUE TITLE
[Feature Request]: Add /banip alias for /ipban

### ISSUE THREAD

**Issue by SrBedrock** [A248/LibertyBans#150]
### I have confirmed that ...

- [X] There is no duplicate feature request.

### Description

1. Add a `/banip` shortcut to the `/ipban` command.
2. Add a `/muteip` shortcut to the `/ipmute` command.
3. Add a `/warnip` shortcut to the `/ipwarn` command.
4. Add a `/kickip` shortcut to the `/ipkick` command.

Commands that already exist:
- `/unbanip` - bans or unbans a player or IP address
- `/unmuteip` - mutes or unmutes a player or IP address
- `/unwarnip` - warns or unwarns a player or IP address

**Comment by A248** [comment]
This should be handled by an alias plugin. It's impractical to maintain many different aliases in LibertyBans itself.
