### ISSUE TITLE
[Feature Request]: Hiding tabcomplete commands if permission is set to false

### ISSUE THREAD

**Issue by 1ntent1on** [A248/LibertyBans#155]
### I have confirmed that ...

- [X] There is no duplicate feature request.

### Description

Hello, would it be possible to add feature to not show all LB commands + aliases , if main permission is set to false? Or just specific perms for each command + alias. Lot of plugins are doing that, sadly LB is not one of them, yet. Currently if player has libertybans.* false, he will be able to see "/libertybans" and all aliases, such as "/ban" etc.
Adding that makes chat more clear for players, as they dont have to see commands that are useless to them, also it help for staff, as they wont get confused by some shown punishments that they dont have perms for. 
Also option to display default Minecraft "unknown command" message would be great, if player isnt able to see that command at all.

**Comment by A248** [comment]
I have implemented everything you asked for.
