### ISSUE TITLE
[Feature Request]: edit: View alt composite punishments in /history

### ISSUE THREAD

**Issue by accLarson** [A248/LibertyBans#157]
### I have confirmed that ...

- [X] There is no duplicate feature request.

### Description

The config.yml has a settings called `use-composite-victims-by-default` which automatically bans both the user and their IP address as if the admin had used the command option `-both`.

I propose an additional command option `-alts` as well as a config setting called something like `use-alt-victims-by-default`.
This new command argument `-alts` would ban all detected alts of the banned player, with the same length and reason.
This new setting would make every ban effectively use `-alts`, similar to `use-composite-victims-by-default` and `-both` .

This is extremely useful because as of right now if an admin finds a hacking player, and executes a ban for 10 days, with `-both` (or with `use-composite-victims-by-default` enabled), the hacking player will get a ban record and the IP will be banned. No alts should be able to join since the IP address was also banned BUT, when the ban is done, there will be no record left on those alt accounts. with the proposed '-alts` argument The admin would be able to view /history <one of the alts> and get a ban history.

**Comment by accLarson** [comment]
You are correct composite ban records in the history would be extremely useful. 

Thanks for the quick response.

If I understand correctly, a composite ban is a ban on a player and their IP address (blocking alts via the IP ban)
Would your proposed alternative solution display a ban history on an alt who never directly received a ban? For example:
PlayerA has an alt, PlayerB.
PlayerA is composite banned. 
PlayerA cannot log on because their UUID and IP Address are banned.
PlayerB cannot log on because their IP Address is banned.
Running `/history PlayerA` displays the ban record.
Currently running `/history PlayerB` displays no record.
Would your alternative solution show a ban record for `/history PlayerB`? Perhaps indicating that it is a composite ban record?

**Comment by A248** [comment]
> Would your alternative solution show a ban record for /history PlayerB? Perhaps indicating that it is a composite ban record?

Yes, this is exactly what I am suggesting.

**Comment by accLarson** [comment]
Beautiful. When do you think you plan to implement this?

**Comment by A248** [comment]
Like in a fairy tale, this feature request was magically foreshadowed in https://github.com/A248/LibertyBans/issues/94. Perhaps this is not surprising, but I choose to believe otherwise.
