### ISSUE TITLE
New API to select punishments before a given time

### ISSUE THREAD

**Issue by A248** [A248/LibertyBans#161]
It is currently possible to retrieve punishments *after* a specified time, but not before. A new API method `seekBefore(Instant, long)` should be added to `SelectionOrderBuilder` to remedy this.

This API addition will serve the staffrollback and warn-actions addons well:
* For the staffrollback addon it will improve efficiency along with (#158).
* For the warn-actions addon, it will enable greater consistency in case multiple warns are issued very quickly, causing overlapping punishment events.

**Comment by FreakyRed** [comment]
Hello, I'd like to work on this issue (along with some others from the list - (if time allows) if possible.

**Comment by A248** [comment]
> Hello, I'd like to work on this issue (along with some others from the list - (if time allows) if possible.

You're more than welcome to. The API method should work similarly to the existing `seekAfter` method -- which is already implemented -- except in reverse.

**Comment by FreakyRed** [comment]
> > Hello, I'd like to work on this issue (along with some others from the list - (if time allows) if possible.
> 
> You're more than welcome to. The API method should work similarly to the existing `seekAfter` method -- which is already implemented -- except in reverse.

Hi, almost done with the implementation. Just want to ask, is there any endpoint for the method to be called that I am missing? Or is the `getPredication` method in `SelectionImpl.java` class the upmost level.

**Comment by A248** [comment]
You will need to modify `SelectionOrder` and `SelectionOrderBuilder`. It should be fairly straightforward to follow the existing example with *seekAfter*. Of course, you will need to adjust everything as necessary when implementing *seekBefore*.

Here are the API entrypoints.

https://github.com/A248/LibertyBans/blob/376ef3b06e4cb2a3fbf04f4ba2834d17849e1ef8/bans-api/src/main/java/space/arim/libertybans/api/select/SelectionOrderBuilder.java#L187-L209
https://github.com/A248/LibertyBans/blob/376ef3b06e4cb2a3fbf04f4ba2834d17849e1ef8/bans-api/src/main/java/space/arim/libertybans/api/select/SelectionOrder.java#L101-L117
