### ISSUE TITLE
Unrelocated libraries in Logger-Velocity

### ISSUE THREAD

**Issue by zRxnx** [A248/LibertyBans#165]
### LibertyBans Version

Command doesnt exist

### I have confirmed that ...

- [X] LibertyBans is up to date
- [X] No similar issue has been reported

### Platform

Velocity

### Description

After the boot there comes a error.
![image](https://user-images.githubusercontent.com/74078713/181860418-819cf36f-c4f1-4627-8dfb-8c50f06b4b5a.png)

**Comment by A248** [comment]
This is a bug in Logger-Velocity and has to be fixed by them. We cannot solve it ourselves.

**Comment by ExceptedPrism3** [comment]
Hello there, we do not use nor shade any form of API that belongs to LibertyBans.

**Comment by gepron1x** [comment]
> Hello there, we do not use nor shade any form of API that belongs to LibertyBans.

That's not the problem. You should relocate postgresql driver in your plugin.

**Comment by A248** [comment]
> Hello there, we do not use nor shade any form of API that belongs to LibertyBans.

With all properly due respect, the PostgreSQL driver doesn't belong to you either. As such, you need to relocate it to your own namespace to avoid conflicts.

Most of the time, the solution is a few lines in your pom.xml and is relatively easy to apply. If you'd like me to create a PR, I'm entirely willing to help.

**Comment by ExceptedPrism3** [comment]
> > Hello there, we do not use nor shade any form of API that belongs to LibertyBans.
> 
> With all properly due respect, the PostgreSQL driver doesn't belong to you either. As such, you need to relocate it to your own namespace to avoid conflicts.
> 
> Most of the time, the solution is a few lines in your pom.xml and is relatively easy to apply. If you'd like me to create a PR, I'm entirely willing to help.

Hello there, I'm aware as well but it wasn't me who integrated the PostgreSQL into the plugin as that addition is in it's own branch and haven't been used in public production. I've contacted the contributer responsable for it so he can do what needs to be done, thank you in advance. You can do PR if you'd like. Any help is appreciated by me :D

**Comment by A248** [comment]
Closing in favor of https://github.com/ExceptedPrism3/Logger/issues/24
