### ISSUE TITLE
[Feature Request]: Make /history show length of ban/mute and time remaining

### ISSUE THREAD

**Issue by Boy0000** [A248/LibertyBans#169]
### I have confirmed that ...

- [X] There is no duplicate feature request.

### Description

Currently its very tricky to find out the original length and remaining time of a ban, would be a nice addition.
Say someone circumvents a ban and you wanna double the length, you can't really find the original banlength easily

**Comment by SnakeAmazing** [comment]
You can use the CheckUser addon to see the remaining time. Also, have you tied adding placeholders to the history messages? %DURATION% and %TIME_REMAINING% are the ones you are looking for.

**Comment by Boy0000** [comment]
thanks for whatever reason i didnt check this... fixed
