### ISSUE TITLE
Question Regarding Configuration with Geyser Server

### ISSUE THREAD

**Issue by TheMattVid** [A248/LibertyBans#173]
Hello! I have recently migrated AdvancedBan to LibertyBans.

I am using LibertyBans 1.0.4 on a Waterfall Proxy. My server allows Bedrock and Java players to join via Geyser plugin on the proxy and Floodgate on the proxy and all backends. In my LibertyBans config, I have the server-type set to GEYSER in the LibertyBans config. The server is not cracked, as all Bedrock and Java users who join must be authenticated.

I am trying to ban a Java player who has not logged in since before the time of migration/installation of the LibertyBans plugin. The plugin fails to do so stating that the player "was not found online or offline". What should I do to make this work?

**Comment by A248** [comment]
LibertyBans allows you to ban directly via the Java player's UUID, which is helpful if the player's name isn't recorded in the database.

For example, to ban me (A248) even if I have never joined your server, you may run `/ban ed5f12cd-6007-45d9-a4b9-940524ddaecf`. This works with or without the hyphens (sometimes you'll have a UUID with hyphens, and sometimes not).

To lookup UUIDs I typically rely on NameMC, a website which tells you this information. Java player UUIDs are public knowledge. https://namemc.com/profile/A248.1.

**Comment by TheMattVid** [comment]
For convenience purposes, would it be possible to add a setting that allows LibertyBans to resolve the UUIDs via Mojang's database even under the 'Geyser' server type? The only Java players able to join are those authenticated with Mojang, so it would be beneficial if the plugin utilized the web-api-resolvers setting for all Java players in the same way that it does when set to the 'Online' setting.

**Comment by A248** [comment]
The reason we currently don't resolve UUIDs under the Geyser server type is that some player names might be Geyser names. For example, `/ban *GeyserPlayer` might result in a UUID lookup for "*GeyserPlayer" if we are not careful. The Mojang API returns an error when this happens.

Now that you have made me consider it, we *could* detect whether the name is from Java or Geyser and decide whether a UUID lookup is possible. That's a worthy feature request.

Ultimately, I want to improve Geyser support by detecting its presence automatically, including the prefix (#43 - our oldest existing feature request). When this happens, specifying the Geyser server type should no longer be necessary, and we will once again differentiate between premium/cracked Geyser servers (as you alluded to, the 'GEYSER' setting does not distinguish with respect to online mode).

**Comment by TheMattVid** [comment]
Thank you, it is very much appreciated! I am looking forward to this implementation, and I will use the suggested workarounds in the meantime.

**Comment by A248** [comment]
This should work on the latest development build. You will have to adjust the config.yml since the `GEYSER` server type has been removed. Let me know if you run into any issues.
