### ISSUE TITLE
[Feature Request]: Leveling punishments

### ISSUE THREAD

**Issue by Angeluuus** [A248/LibertyBans#180]
### I have confirmed that ...

- [X] There is no duplicate feature request.

### Description

I would like to be able to add different levels for a reason in a config (reasons.yml).
e.g.: 
1. Hacking punish = 30d
2. Hacking punish = 60d
3. Hacking punish = permanently

**Comment by MCMDEV** [comment]
IMO this should be implemented as an addon.
All sorts of additions, some having more impact on how the plugin works (Exemptions) and some just adding a new command.
I like the plugin being as lightweight as it is right now, essentially just being capable of doing very essential punishments.

**Comment by A248** [comment]
Layouts are now available as an addon with API support in the core plugin. Links:
* [Development builds](https://ci.hahota.net:8443/job/LibertyBans/)
* [Documentation](https://docs.libertybans.org/#/Addons?id=layouts)
