### ISSUE TITLE
[Bug Report]: Warn Actions Addon causes exception on /warn 

### ISSUE THREAD

**Issue by RhythmicSys** [A248/LibertyBans#186]
### LibertyBans Version

LibertyBans 1.1.0-SNAPSHOT-2022-11-27T20:42:47Z

### I have confirmed that ...

- [X] LibertyBans is up to date
- [X] No similar issue has been reported

### Platform

Spigot/Paper

### Description

Getting an exception when I try to `/warn` when using the warn actions addon

[Exception](https://pastebin.com/TZwVz8Np)
[Full Log](https://mclo.gs/3b62sR5)
[Config](https://pastebin.com/QTrz1Gef)
[Addon config- I did not change from default](https://pastebin.com/Tvzi61jm)

installed addons:
`addon-command-checkpunish-1.1.0-SNAPSHOT.jar`
`addon-command-checkuser-1.1.0-SNAPSHOT.jar`
`addon-command-staffrollback-1.1.0-SNAPSHOT.jar`
`addon-warn-actions-1.1.0-SNAPSHOT.jar`

**Comment by A248** [comment]
Reproduced and solved. Thanks for the report.
