### ISSUE TITLE
[Feature Request]: Add ability to ban Bedrock Edition users even when Floodgate isn't installed on proxy

### ISSUE THREAD

**Issue by Folas1337** [A248/LibertyBans#195]
### I have confirmed that ...

- [X] There is no duplicate feature request.

### Description

I'll just copy what I wrote on Discord to explain my situation:
```
I've had a really strange issue on my network today but I might have to explain the setup as it might explain why it happened but I wanted to make sure by asking here :)

I have 4 proxies in total, two of them run Geyser and serve only bedrock edition users and two running with no Geyser. All of them are using the same Maria DB for libertybans and are synced up through RedisBungee. A new bedrock edition user joined and I tried banning them but libertybans told me the user "was not found online or offline" which raised the question why this might have happened.

Wouldn't the user and it's UUID be stored in the database and I should definitely be able to ban them or could I have configured something wrong so this didn't work? 🤔
And I'm separating Geyser and non Geyser to keep downtime low so whenever Geyser needs to be updated, it doesn't affect the Java users :)
```

To which I got the reply that you can't ban Bedrock Edition users from a proxy that doesn't have Floodgate installed and if I wanted it to be possible I shall open an feature request which I hereby did.

Hope that's enough information otherwise I'm willing to provide some more.

**Comment by Folas1337** [comment]
Any chance we could potentially see this in the next minor update release (1.2.0)? :) I'd greatly appreciate that!

**Comment by A248** [comment]
We are technically still releasing 1.1.0. But that works in your favor. Since this overlooked possibility of configuration ("bug", if you prefer) was missed when implementing #43 , I believe it is fair to correct this omission of foresight while we are still in 1.1.0. Also, it's relatively easy to implement.

So we will see this feature relatively soon. Thanks for the reminder; you made me think more about it.

**Comment by Folas1337** [comment]
Woohoo, thanks for this! :)
