### ISSUE TITLE
.

### ISSUE THREAD

**Issue by SnowDriven9** [A248/LibertyBans#202]

**Comment by A248** [comment]
It would require a lot of changes, potentially breaking, to have entirely separate messages for punishments depending on whether they are permanent or temporary.

I would be willing to add a variable for a punishment depending on whether it is permanent or temporary. However, it is too much of a rabbit hole to segment the entire message based on details such as whether it is permanent or temporary. Generally speaking, LibertyBans treats all variants of punishments the same, no matter details such as the type, temporary/permanent status, IP/user victim, or other. We then use variables to differentiate punishment messages.
