### ISSUE TITLE
[Feature Request]: Rogue staff protection

### ISSUE THREAD

**Issue by USBCharger** [A248/LibertyBans#203]
### I have confirmed that ...

- [X] There is no duplicate feature request.

### Description

It would be nice to add in a permission based protection for a rogue staff member (ie: hacked account/typo, etc.) to prevent banning higher ranking staff members.

(I only did a quick scan to see if this exists and found nothing, if it did and I missed it or a feature request that asked for this, I'm sorry, I'm sleepy right now lol)

**Comment by SrBedrock** [comment]
Addons already exist for this: https://docs.libertybans.org/#/Addons?id=exemption

**Comment by A248** [comment]
Closing as already implemented

**Comment by USBCharger** [comment]
Gotcha, thank you!
