### ISSUE TITLE
[Feature Request]: Tiered warning categories to line up with 

### ISSUE THREAD

**Issue by Nachtmaken** [A248/LibertyBans#205]
### I have confirmed that ...

- [X] There is no duplicate feature request.

### Description

I used to use a plugin called Advanced Warnings, which would allow you to define warning categories that would have punishment (commands) auto-run based on how many warnings were issued. Litbans already has this feature and would love to see it here (added in version 2.10).
For example:

```
categories:
  spam:
    1: "tempmute %player% 10m"
    2: "tempmute %player% 1h"
    3: "tempmute %player% 24h"
    4: "tempban %player% 24h"

```

Adds some complexity, but imo, adds a lot more value to warnings as a moderation tool. It allows server staff to just issue warnings as needed and not have to think about what punishments to give (also allows some staff to not have permission to mute/ban/etc directly, and requires them to issue the appropriate numbers of warnings first.

**Comment by A248** [comment]
We are implementing this feature request as #180 and work is already under way.
