### ISSUE TITLE
[Feature Request]: WebSite for ban list

### ISSUE THREAD

**Issue by Xteri08** [A248/LibertyBans#218]
### I have confirmed that ...

- [X] There is no duplicate feature request.

### Description

hello there i would like to suggest you to add an interference so that we can actually list the banned players on the website by hosting it like in litebans it would defienitly help a lot of server owners.

**Comment by A248** [comment]
A fellow community member wrote a web interface for LibertyBans. Here it is: https://github.com/Dimitri-Fustic/Liberty-Bans-Web

If you'd like to contact the maintainer, Dimitri is available also on our Discord server.

**Comment by Xteri08** [comment]
thans sir

**Comment by hockeymikey** [comment]
@Xteri08 No you're wrong. Java should be more efficient than say php which is interpreted. A small little proxied jar like the interface is not a big deal. Its no different than having php-fpm running basically.
