### ISSUE TITLE
add legacy version for  java 8

### ISSUE THREAD

**Issue by ant-7802** [A248/LibertyBans#234]
I wanna use protocolsupport 1.12.2 but it doesn't work on java 17

**Comment by A248** [comment]
LibertyBans has required Java 11 from its inception, so this will not happen.

If you need assistance migrating from Java 8 to Java 17, I am willing to provide it. I've spent a lot of time on such migrations in other contexts.

The 1.0.x release track, as I mentioned on Discord, supports Java 11. Per our [Versioning and Support Policy](https://docs.libertybans.org/#/Versioning-and-Support-Policies), it will continue to be maintained for at least 1 month following the release of 1.1.0. Currently, we're on 1.1.0-RC1, which is close to 1.1.0, but not there yet, meaning 1.0.x is supported for critical bug fixes and user assistance.
