### ISSUE TITLE
[Bug Report]: Not ban users

### ISSUE THREAD

**Issue by zertex** [A248/LibertyBans#247]
### LibertyBans Version

LibertyBans 1.1.0-RC1

### I have confirmed that ...

- [X] LibertyBans is up to date
- [X] No similar issue has been reported

### Platform

Spigot/Paper

### Description

First ban command write correct info about ban on screen, but player can login...
After unban: "is not banned"
After next ban command I receive message: "is already banned"

A player can login any way... why?

**Comment by zertex** [comment]
Drop all database, work fine

**Comment by A248** [comment]
Under the default configuration, this can happening if you're running a cracked server and you tried to ban a player who is not online. The default configuration assumes you're running a premium server, so it will look up the player's Mojang UUID.

This doesn't explain why unbanning would stop working, but it looks like you solved the issue regardless.
