### ISSUE TITLE
How do I set the language?

### ISSUE THREAD

**Issue by Airzhcn** [A248/LibertyBans#254]
Hello, I don't know how to set the language

**Comment by A248** [comment]
There is a language option in the config.yml. Set it to the corresponding filename inside the messages/ directory. For example, for French, set "fr" which matches messages_fr.yml.

**Comment by Airzhcn** [comment]
> config.yml中有一个语言选项。将其设置为 messages/ 目录中的相应文件名。例如，对于法语，设置与messages_fr.yml匹配的“fr”。

Thank you!!
