### ISSUE TITLE
[Bug Report]: Fatal Error when writing in chat while muted

### ISSUE THREAD

**Issue by xNiika** [A248/LibertyBans#257]
### LibertyBans Version

LibertyBans 1.1.0-RC2

### I have confirmed that ...

- [X] LibertyBans is up to date
- [X] No similar issue has been reported

### Platform

Velocity

### Description

If a user is sending a chat message while beeing muted it will produce an fatal error and kicks the player:
```console
[16:36:45 FATAL]: A plugin tried to cancel a signed chat message. This is no longer possible in 1.19.1 and newer. Disconnecting player <playername>
[16:36:45 INFO]: [connected player] <playername> (/<ip-adress>) has disconnected: A proxy plugin caused an illegal protocol state. Contact your network administrator.
```

**Comment by KoxSosen** [comment]
Hello! Thank you for reporting. I think this issue is mainly caused by the new chat signing system, which frankly proxies do not implement just yet. I would recommend installing [SignedVelocity](https://github.com/4drian3d/SignedVelocity) to fix this issue temporary.

**Comment by NixNux123** [comment]
Hello, i have the same issue. I tried SignedVelocity but after that the muted user could write. Does this happened only to me?

**Comment by SrBedrock** [comment]
> Hello, i have the same issue. I tried SignedVelocity but after that the muted user could write. Does this happened only to me?

Nope, it happens to me too.

**Comment by A248** [comment]
If you're using SignedVelocity and it allows muted players to chat, that relates to your backend server's chat plugins. There are two possibilities:
1. You need to try using [SignedVelocity-Legacy](https://github.com/4drian3d/SignedVelocity-Legacy/tree/main), a variant of SignedVelocity which accounts for legacy chat plugins.
2. The chat plugin you're using is broken and it is not respecting the cancelation status of the chat event.

**Comment by NixNux123** [comment]
Hey, thank you very much. For me I need to fix my Chatsystem to check if the message was cancelled.
