### ISSUE TITLE
[Bug Report]: Unknown collation: 'utf8mb4_0900_ai_ci'

### ISSUE THREAD

**Issue by ChristopherPS96** [A248/LibertyBans#258]
### LibertyBans Version

1.1.0_RC2

### I have confirmed that ...

- [X] LibertyBans is up to date
- [X] No similar issue has been reported

### Platform

Spigot/Paper

### Description

```
[14:38:33 INFO]: [com.zaxxer.hikari.pool.HikariPool] LibertyBansPool-MySQL - Added connection org.mariadb.jdbc.Connection@5b729414
[14:38:34 WARN]: java.sql.SQLException: Unknown collation: 'utf8mb4_0900_ai_ci'
[14:38:34 WARN]: at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:130)
```

This warning do I get on my g-portal minecraft server (Paper 1.20.1).
It happens on startup and prevents the creation of a table in my database.

**Comment by A248** [comment]
This would suggest your database doesn't support `utf8mb4`, which is strange. Can you tell me the MySQL version you're using? I need more information to figure this out.

**Comment by ChristopherPS96** [comment]
I'm not quite sure. A g-portal server gives me access to phpmyadmin , where I can look at the databases (with limited rights tho).

Maybe the information on the right side helps you there.

![grafik](https://github.com/A248/LibertyBans/assets/39082942/a15975d6-b041-4ddd-a58b-db0d88360dfe)

**Comment by ChristopherPS96** [comment]
https://dba.stackexchange.com/questions/248904/mysql-to-mariadb-unknown-collation-utf8mb4-0900-ai-ci

Seems like this is an issue with MariaDB not supporting 9.0.0 Unicode

**Comment by ChristopherPS96** [comment]
Thanks for the answer.

Yeah, It's really strange, and I too suspect it's something that is specific to my database. Because I have a second minecraft server, that is also on g-portal, that works perfectly fine with libertybans.

For me personally, this isn't anything drastic, and I can perfectly fine use a local database. But I just wanted to bring attention to it. 

What is strange. The only plugin, that had I the same issue with, was Domain. 
They have given me a new jar file, where they have removed all collates out of their "create table" queries. And now it works fine also. Not saying, that what you should be doing, just wanna share the information I have.

**Comment by A248** [comment]
I'm going to close this issue since LibertyBans works fine on your other g-portal database, and I strongly suspect a database misconfiguration. Maybe resetting or redownloading your database's character sets may help. Not sure.
