### ISSUE TITLE
Suggestion: Bukkit addon for command registering

### ISSUE THREAD

**Issue by KoxSosen** [A248/LibertyBans#26]
Hello! 

I'm having issues with using the ban commands from the proxy with plugin like an anticheat in the backend. I would like to use the ban commands, and give the ability to plugins to use the ban commands in Bukkit as well.

I have LibertyBans running in Velocity, but I can't use libertybans ban commands with plugins from the backend (Bukkit) that use ban commands, since the backend server does not knows about the plugin. This could be solved by a Bukkit addon, that registers the libertybans ban commands in the backend as well for plugins.

Please let me know what do you think! ^_^

**Comment by A248** [comment]
Luckily for you, there are existing plugins made for this purpose. I get asked this question a lot, so here are the ones I know, in alphabetical order:

[CommandBrothers](https://www.spigotmc.org/resources/commandbrothers-%C2%BB-send-console-commands-from-bukkit-to-bungeecord.44901/) - closed source but I'm guessing uses plugin messages
[CommandSync](https://www.spigotmc.org/resources/commandsync.115/) / [CommandSyncReborn](https://www.spigotmc.org/resources/commandsync-reborn.63194/) - uses direct socket connections to its own command server
[ExecuteEverywhere](https://www.spigotmc.org/resources/executeeverywhere.524/) - uses Redis, but last updated 2015
[ExecuteEverywhereReloaded](https://github.com/A248/ExecuteEverywhereReloaded) - uses Redis, recoded version of ExecuteEverywhere I made upon request
[HopeCommander](https://www.spigotmc.org/resources/hopecommander.81455/) - uses BungeeCord plugin messages

I do not recommend CommandSync(Reborn). Considering how few lines of code are necessary in the other plugins listed here, CommandSync is completely over-engineered by comparison and still comes out worse in its attempt to reinvent a message broker.

BungeeCord plugin messages have the most compatibility and least requirements, but the plugin messaging channel does not have any guaranteed semantics about delivery. Also, plugin messaging requires a player connected to the server through which the commands are sent.

If you have Redis installed or are willing to install it, I would suggest that. I don't know of any plugins like these which use Apache Kafka or RabbitMQ, but again noting how simple these plugins are to make, it could be done quite easily.

**Comment by KoxSosen** [comment]
Thank you so much for the suggestions! 

I contacted HopeCommanders developer for Velocity support, but it seems like he doesn't knows how to code velocity plugins. 
![image](https://user-images.githubusercontent.com/67807644/107662364-7fc78180-6c8a-11eb-9972-1cfdaed0ef2a.png)

ExectuteEverywhereReloaded looks really promising, however I don't have that much of a Redis experience, does using it requires a Redis server, or is it just a Redis installation?

**Comment by A248** [comment]
That's okay. Considering HopeCommander's source code includes about 3 classes for bungeecord, any developer who *does* know the velocity API would be able to add support without much difficulty. If you have a developer who works with you, that would be a relatively easy task.

I've never used Redis myself to be honest. What's the difference between a Redis server and an installation? I'd expect them to be the same thing.

**Comment by KoxSosen** [comment]
Huh, I have no clue what is the difference between a redis and a redis server installation sorry. One of them only installs the packages required the run a redis app maybe? 

I checked HopeCommanders bungee code, and as you said it doesn't looks that hard to do the same with velocity. At the moment I don't have any developers who works with me closely, so I quess it's time to learn the Velocity api ^_^

**Comment by KoxSosen** [comment]
Fixed the issue.
