### ISSUE TITLE
[Feature Request]: 1.21 support when

### ISSUE THREAD

**Issue by MaxKanoe** [A248/LibertyBans#272]
### I have confirmed that ...

- [X] There is no duplicate feature request.

### Description

i'm a little impatient :(

**Comment by gepron1x** [comment]
Bro have you even tried running LibertyBans on 1.21 server?

**Comment by MaxKanoe** [comment]
> Bro have you even tried running LibertyBans on 1.21 server?

yeah, /mute, /warn, and any of the list commands don't work. tbh I should've just made this a bug report about that, but I kind of thought it was just because it's outdated.

**Comment by KoxSosen** [comment]
Hello! Thanks for the heads up. Which server platform are you using, and would you be able to share a full log?

I tried replicating the mentioned issue on a Paper 1.21 server (which is experimental currently), however for me all of the mentioned features worked as intended.

**Comment by KoxSosen** [comment]
Thank you! I believe this is possibly related to one of the plugins, or the older 1.21 Paper release build you have installed. For me LibertyBans version `v1.1.0-SNAPSHOT-2024-05-06T17:54:45Z` (latest dev build from the ci) enables correctly on Paper experimental build version `1.21-49-master@b0ef3ca (2024-07-09T15:22:17Z)`.

**Comment by A248** [comment]
I looked at your latest.log file. This is an unrelated problem caused by a conflict with another plugin. I suggest removing plugins and restarting the server until it goes away, and then you will know the culprit. Sadly there's not an easier way (although you can use the "remove half" method to speed things up).

**Comment by DidsheMa** [comment]
1.1.0-RC2 works fine for me on Velocity 1.21 :)
