### ISSUE TITLE
[Feature Request]: Update Guice

### ISSUE THREAD

**Issue by BAD7777** [A248/LibertyBans#274]
### I have confirmed that ...

- [X] There is no duplicate feature request.

### Description

I noticed that the project is using an older version of Guice (6.0.0), which utilizes deprecated JavaX annotations. To avoid potential compatibility issues and to take advantage of new features and improvements, I suggest updating Guice to a newer version.

**Comment by A248** [comment]
We don't use Guice at all; rather, we use Jakarta annotations with a simpler injector library.

**Comment by A248** [comment]
Okay just to clarify: Velocity uses Guice to instantiate plugins. LibertyBans itself doesn't use Guice. However, the entry point for the velocity platform implementation uses Guice in 1 class and exactly 1 class.
