### ISSUE TITLE
Category question

### ISSUE THREAD

**Issue by mcTusa** [A248/LibertyBans#278]
Greetings, can You please tell me, how can I use categories? Like I want to ban player from category duels, but the banned player still can join lobby. (I am using velocity.)

**Comment by A248** [comment]
You will need to install LibertyBans on all of the backend servers, and configure each backend server with the scopes/categories you want to apply to it. Then you can run `/ban A248 --category=duels Bye Bye` to ban me from all your duels servers.

See also the wiki: https://docs.libertybans.org/#/Scoped-Punishments?id=commands
