### ISSUE TITLE
[Feature Request]: Simple Voice Chat support for mutes

### ISSUE THREAD

**Issue by xllifi** [A248/LibertyBans#280]
### I have confirmed that ...

- [X] There is no duplicate feature request.

### Description

Pretty straightforward - cancel microphone packets from muted players and send feedback to actionbar.

**Comment by KoxSosen** [comment]
Hello, and thank you for your suggestion! 

Unfortunately I'm not sure if something like this will be added to LibertyBans, as supporting 3rd party plugins, and integrations is usually done via the API(s) of the respective platform(s). I've personally created a resource for this purpose which you can check out [here](https://github.com/KoxSosen/SimpleVoiceBans), however it's not an official project from the LibertyBans team, just a fun project of mine.

**Comment by xllifi** [comment]
Thank you, this is exactly what I need! Do you have any plans on publishing to modrinth, Hangar, SpigotMC, CurseForge or other platforms?
