### ISSUE TITLE
[Bug Report]: The mute doesn't works

### ISSUE THREAD

**Issue by XPaladiumyX** [A248/LibertyBans#282]
### LibertyBans Version

LibertyBans 1.1.0-RC2

### I have confirmed that ...

- [X] LibertyBans is up to date
- [x] No similar issue has been reported

### Platform

Velocity

### Description

![image](https://github.com/user-attachments/assets/5148ea7e-52aa-49d3-9705-6ae8e282fe03)
Hello, i make this report to say that when you mute someone, the mute punishement message shows but it doesn't works, peoples messages are still appearing.
I am on Velocity i never had this problem before and it just hapenned recently.

**Comment by A248** [comment]
I think you figured this out, but the lesson is that SignedVelocity has to be installed on Velocity.

**Comment by Xbani** [comment]
Hi, I have exactly the same issue. 
Proxy : 
- Velocity 3.4.0
- LibertyBans 1.1.1
- SignedVelocity-Proxy 1.3.0

Lobby Server :
- Paper 1.21.8 - 21
- LibertyBans 1.1.1
- SignedVelocity-Paper 1.3.0

@XPaladiumyX How did you fix it ?

**Comment by A248** [comment]
@Xbani I looked at the SunLight chat code, and I remembered that you are using SignedVelocity.

SunLight uses the AsyncPlayerChatEvent. So, you need to install SignedVelocity-Legacy, because the regular SignedVelocity does not handle the AsyncPlayerChatEvent. Please try that and see if it works.
