### ISSUE TITLE
Error on import of data from AdvancedBan

### ISSUE THREAD

**Issue by 4drian3d** [A248/LibertyBans#39]
When using the command "/libertybans import advancedban" it gives the following error https://pastebin.com/FASYw6RY . And when trying to delete the user's line where it would give the error or change from ONLINE (default) to OFFLINE mode, it gives the same error.
Versions:
This server is running Tuinity version git-Tuinity-"1382473" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
AdvancedBan v2.3.0
LibertyBans v0.7.4 and v0.7.5-pre-3

**Comment by A248** [comment]
Thanks for the report. If you are also willing to provide some AdvancedBan data for testing purposes, that would help weed out any remaining bugs (if not, that's fine too). I will scramble any IP addresses like I did for the LiteBans data.

**Comment by 4drian3d** [comment]
If you are referring to the AdvancedBan data, sure, I can give it to you, if you need some other data to improve the plugin, better. https://www.mediafire.com/file/4xdiz93ky65rqb2/AdvancedBanData.rar/file

**Comment by 4drian3d** [comment]
I just compiled the resource with the new changes, and it seems to give the same error https://pastebin.com/ifpdzier

**Comment by A248** [comment]
If you are compiling from source, be sure to use the LibertyBans_Executable jar, as described here:

https://github.com/A248/LibertyBans/blob/master/CONTRIBUTING.md#compiling-and-running-the-current-source

**Comment by 4drian3d** [comment]
The data import is working, thanks for fixing it :D
One question, if I want to move the data from AdvancedBan(Spigot) to LibertyBans(Velocity), how can I do it correctly?

**Comment by A248** [comment]
Run the import on Spigot, then copy the LibertyBans plugin folder to Velocity.

All of the configuration and data is fully platform-independent, so it is safe to copy across platforms.
