### ISSUE TITLE
Automatically determine Floodgate prefix

### ISSUE THREAD

**Issue by A248** [A248/LibertyBans#43]
f29ac7af2b591dd4e6649b5e300e8da92be853ad adds initial support for Geyser, but requires users to specify the prefix manually.

It would be better to use the Floodgate API to retrieve this username. This can be done once the Floodgate 2 API is stable and in use.

**Comment by KoxSosen** [comment]
The Floodgate V2 api seems stable now. There is a method to get the player prefix in the API ( https://github.com/GeyserMC/Floodgate/blob/50e6676bfc80b0e6ff8f708f39d7ef153a3b8b84/api/src/main/java/org/geysermc/floodgate/api/FloodgateApi.java#L48 ), not sure if this is what we are looking for.

**Comment by A248** [comment]
We are somewhat also waiting on https://github.com/GeyserMC/Floodgate/issues/255 so that we don't on a SNAPSHOT version of the Floodgate API. I've had too much trouble with snapshots in the past to want to rely on them any more than absolutely necessary.
