### ISSUE TITLE
Allow easy extension of the core plugin with addons

### ISSUE THREAD

**Issue by A248** [A248/LibertyBans#46]
Many punishment-tangential features can be implemented in other plugins using the API, features which need not be added to the core plugin. Using the API requires creating an entirely separate plugin. This is fine for most cases, and should be the goal when developing other plugins with LibertyBans integration.

For new features created by the same maintainers of LibertyBans, it would be onerous to recreate much of the implementation of the core plugin. For example, abstraction across platforms will never be exposed in the API. Rather than re-make the core infrastructure of the codebase, an addon mechanism will allow extension of the core plugin.

**Comment by ahdg6** [comment]
Greetings. I want to ask something about add-on system. What will it look like? The plugins I ever saw which has an add-on system is [Cartographer](https://github.com/BananaPuncher714/Cartographer2), It allows other developers to create add-on with a common template and user easily drop add-on into `plugins/Cartographer2/addons` to install. What's more, That plugin has a small system to load and unload add-on on runtime.

Would the add-on system of LibertyBans be like this? Considering LibertyBans is a multi-platform plugin. I thought that will be a good implementation. 

Thank you~

That plugin add-on use a `modules.json` to contain all required information, **example**
![图片](https://user-images.githubusercontent.com/36436808/158013316-44d8ea55-adf6-4b74-8235-209a3dff75e4.png)

**Comment by A248** [comment]
The addon system I have developed looks quite similar. We use the `addons` folder to load addons and their configuration. Users drop addon jars in that folder, and addons are loaded at startup. There is currently no functionality to reload addons at runtime (and no such functionality is planned -- addon installations don't cost any extra performance weight, so I don't see a need to load/unload them except at startup/shutdown).

Unlike Cartographer, however, LibertyBans addons are intended only for development by maintainers themselves. We do not intend anyone to create an addon, as addons have deep access to LibertyBans internals. Some addons may require updating alongside updates to LibertyBans. Indeed, updates to LibertyBans will be released at the same time as updates to addons. The addon system is merely a way to separate certain auxiliary functionality from the core plugin, to avoid feature bloat and improve overall maintainability.

For other developers, we expect the LibertyBans API to be sufficient. If there is a need which cannot be met by the API, developers should ask us or post an issue; we will expand the API as appropriate.

**Comment by A248** [comment]
For those who find it interesting:

I decided to use the ServiceLoader rather than a .json file to load addons. The ServiceLoader is a readily available mechanism in the standard library to detect plugin-like services and load them without having to manually scan jar archives. The downside of the ServiceLoader is a deficit of metadata; the ServiceLoader does not provide details such as "author", "version", "description". However, for our purposes, addons do not need to report this information; the name of the LibertyBans addon is sufficient.

It would have been theoretically possible for any other plugin system, including Bukkit, to have been designed using the ServiceLoader. However, since these plugin ecosystems desire additional metadata and ease of use, relying on a resource file -- whether it is plugin.yml, velocity-plugin.json, modules.json, sponge-plugin.json -- is more approachable. Creating a file called `META-INF/services/org.bukkit.plugin.Plugin` containing the name of your main class is apt to confuse new plugin developers, whereas creating a file `plugin.yml` is much easier to learn. Also, the metadata difficulty of the ServiceLoader could be circumvented by further complicating the service interface, but likewise, this would pose additional confusion to new developers.
