### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by Adriianh** [A248/LibertyBans#47]
I recently installed the plugin on my server (Purpur 1.16.5 with **Java 16**) and got this error, https://pastebin.com/nzg6hY0Q. As you can see, the plugin is not enabled correctly.

**Comment by bugattiboy01** [comment]
Are you using venture by any chance?

**Comment by A248** [comment]
Here's the problem:

> [21:25:01] [Server thread/WARN]: [LibertyBans] An unknown plugin has shaded the library 'HikariCP' but did not relocate it. This may or may not pose problems. Contact the author of this plugin and tell them to relocate their dependencies. Unrelocated class detected was com.zaxxer.hikari.HikariConfig

Please try starting the server without your plugins and then gradually re-adding them until you find the one which is causing the issue.

You can also give me your plugins list and I may be able to spot the problematic one. VentureChat and JPremium are known misbehavers. JPremium is aware of the issue; not sure what's going on with VentureChat though the issue has been reported to them as well.

**Comment by bugattiboy01** [comment]
Venture chat basically said. It works with other plugins so it's your problem not mine.  But a248 does have a fix for venturechat if it is that plugin
