### ISSUE TITLE
PostgreSQL support

### ISSUE THREAD

**Issue by m4nya** [A248/LibertyBans#48]
Yesterday, i had a conversation about LiteBans and LibertyBans. My opponent said that he hates MariaDB/MYSQL and uses Postgre only, and that was the only reason of using LiteBans for him. Why wouldnt break LiteBans monopoly and add PostgreSql support? 😁

**Comment by A248** [comment]
FYI if you intend to use Postgres on LibertyBans 1.0.0, here is the version requirement:

PostgreSQL 12 or later will be required. Database versions 11 and earlier lack certain functionality, so in 1.0.0 these older versions of Postgres will not be supported.
