### ISSUE TITLE
"permit-blank: false" does not work

### ISSUE THREAD

**Issue by LaurenceBarnes** [A248/LibertyBans#49]
Using:

LibertyBans build-17
Velocity 1.1.8

Unfortunately, prohibiting blank permissions does not work. People can still punish players for no provided (custom) reason, causing the default reason to be shown only

in addition, the whole section is a bit weird:

```
reasons:
   # If the above is true, what is the default reason to use when staff do not specify a reason?
  default-reason:: 'No reason stated.'
   # Are blank reasons permitted?
   # If blank reasons are not permitted, staff must specify the full reason
   # If blank reasons are permitted, the default reason is used
  permit-blank: false
```

what is the "above" that is supposed to be true? Above it, there is only the duration permission section, but if I understand correctly it is irrelevant whether duration perms are true or false

thanks in advance!

**Comment by A248** [comment]
The current behavior (which the comments are wrong about) is that, if empty reasons are permitted, an empty reason is used, otherwise, the default reason is used.

Probably, what I will do is introduce a three-valued option.

**Comment by LaurenceBarnes** [comment]
so basically I would need to remove the default reason?
Yeah, a three-valued option (and a fix of the explanation) would be awesome :3

**Comment by A248** [comment]
> so basically I would need to remove the default reason?

The behavior you're looking for, to fail the command when no reason is specified, is not currently available.

I will add this to the 0.8.0 release which is tentatively scheduled within a week, but no guarantees.

**Comment by LaurenceBarnes** [comment]
oh rip :(

well looking forward to it either way :D
