### ISSUE TITLE
Documentation for duration permission is slightly off

### ISSUE THREAD

**Issue by LaurenceBarnes** [A248/LibertyBans#51]
heyo, I noticed that the docs need small adjustments. For duration permissions, it is no longer `libertybans.ban.dur.<timespan>`, but `libertybans.dur.ban.<timespan>` instead.

also, the sentence "The timespan follows the same format as for commands. arimbans.ban.dur.6d grants permission to ban for six days at most." is a bit confusing, as the mentioned permission starts with "arimbans" instead of "libertybans" ^-^

**Comment by A248** [comment]
Thanks, this was a bug. It should be fixed with the latest build.

The format `libertybans.dur.ban.<timespan>` will be supported for compatibility purposes until 1.0.0. I recommend using `libertybans.ban.dur.<timespan>` where possible.

Documentation has been updated accordingly.

**Comment by LaurenceBarnes** [comment]
Oh i see, thanks! Luckily that's a pretty simple thing to change back in LuckPerms ^-^
