### ISSUE TITLE
Tab completion Semi Broken - Velocity

### ISSUE THREAD

**Issue by BumbleTree** [A248/LibertyBans#54]
Liberty bans is on the Velocity proxy and tab completion only semi works

/ban (tab) scrolls through the names

However if you start to type the first letter of any of the names. The tab completion no longer appears.

**Comment by LaurenceBarnes** [comment]
on which build are you?

**Comment by bugattiboy01** [comment]
Was on 7.2.4 Or something similar. Just from memory. However now i am on the 8.0.0 Snapshot. And still same issue

**Comment by A248** [comment]
Tab completion is quite environment-specific. Could you provide the versioning setup you discovered this issue on? Client MC version, server MC version, and even Velocity version would be helpful.

**Comment by bugattiboy01** [comment]
This server is running Airplane version git-Airplane-55 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 68a68ae on HEAD)
1.17.1 client

Velocity - 3.0.1 snapshot Build 45

Latest version of al software and Libertybans itself as of 23/07/21
