### ISSUE TITLE
website gui

### ISSUE THREAD

**Issue by aglarcz** [A248/LibertyBans#55]
Hi, would it be possible to add website gui for libertybans please? something like this for example: https://banall.pokeland.cz/bans.php

I would do it myself but i am not familiar with PHP.

**Comment by gepron1x** [comment]
Hello! Check out @NamelessMC. However, libertybans website is in development right now.

**Comment by gepron1x** [comment]
https://github.com/samerton/Nameless-Infractions/commit/b347fff7957161644c962b7e4b0cdce54b379d08

**Comment by aglarcz** [comment]
Atleast something, thanks for info.

**Comment by Drazee** [comment]
Hello, any new update on website?

**Comment by A248** [comment]
@Drazee , I was not planning to add a website to LibertyBans anytime soon. However, Nameless-Infractions provides a website and I typically recommend it (although I've never used it myself).

**Comment by A248** [comment]
A fellow community member wrote a web interface for LibertyBans. Here it is: https://github.com/Dimitri-Fustic/Liberty-Bans-Web

If you'd like to contact the maintainer, Dimitri is available also on our Discord server.
