### ISSUE TITLE
Add the ability to auto-punish when a player reaches certain number of active /warns

### ISSUE THREAD

**Issue by Braynblocks** [A248/LibertyBans#62]
Based on the discussion I saw on the Discord server, I think it will be a good feature that when a player reaches a specified amount of active /warns, a specified punishment will be applied on the player. I made a sample config for it as well:

![image](https://user-images.githubusercontent.com/68334512/129447753-65564e32-d1d3-42d8-b427-1dc1d2c87832.png)

**Comment by A248** [comment]
I realized this feature can be quite easily provided by another plugin, with the help of the LibertyBans API.

As such, I don't think this feature should be in LibertyBans. However, creating another plugin which fulfills this feature is relatively simple. All you'd need to do is find a developer who is willing to use the LibertyBans API.

**Comment by A248** [comment]
We will implement this feature as an addon.

**Comment by A248** [comment]
The warn actions addon now implements this functionality: https://ci.hahota.net/job/LibertyBans/
