### ISSUE TITLE
Exempt permission for being targeted by /alts and command to manually remove saved logins

### ISSUE THREAD

**Issue by D3adhkwen** [A248/LibertyBans#64]
The implementation of a permission to exempt a player from showing in /alts or autoshow.

The implementation of a command with permission for example `/alts delete` or `/alts remove` to unlink a player name from other accounts.

**Comment by A248** [comment]
For the permission to exempt a player from /alts, what should happen if a staff member uses `/alts <player with the exempt permission>`? Do you want the command to be denied with a message such as "You may not alt-check this player"?

**Comment by D3adhkwen** [comment]
Yes, I think that would be very useful. The message sounds good to me as well.

**Comment by A248** [comment]
The /alts command allows targeting offline players, but it is impossible to perform permission checks for offline players. None of the platforms (Spigot/Paper, Velocity, BungeeCord) provide standard perms of querying offline permissions; proxies do not even offer the concept of an offline player.

At most, LibertyBans could perform the exempt permission check if the target player is online. However, this would lead to surprising and error-prone behavior, and I would like to avoid surprises in the feature set offered by LibertyBans.

Therefore, the exempt permission for /alts unfortunately can't be implemented. Unless, of course, a worthy solution can be found to offline player permission checks.

**Comment by D3adhkwen** [comment]
Unfortunate but I can understand. Is it still possible to implement the ability to remove saved logins? If yes, that would still be very useful.

**Comment by A248** [comment]
> Is it still possible to implement the ability to remove saved logins? If yes, that would still be very useful.

Yes, it has been done.
