### ISSUE TITLE
[Feature Request] Ability to show player name in ban announcement instead of IP when executing IP bans

### ISSUE THREAD

**Issue by D3adhkwen** [A248/LibertyBans#65]
This is the current situation
![image](https://user-images.githubusercontent.com/38313757/130412472-2e74b92b-2e45-4501-912d-039cf456da0d.png)

This could be concerning for the players as their IP will get exposed for everyone to see.

Suggestion:
1. Make IP Ban to show player name in public announcement OR
2. Add permission `libertybans.ban.ip.notify` and remove IP bans from `libertybans.ban.notify`

**Comment by A248** [comment]
The first suggestion is already implemented, see https://github.com/A248/LibertyBans/issues/33

You may use the %TARGET% variable which will use the player name instead.
