### ISSUE TITLE
Failed database migration

### ISSUE THREAD

**Issue by DJelly4K** [A248/LibertyBans#69]
![image](https://user-images.githubusercontent.com/68630033/133925480-8fd1e7e4-5fd6-4353-ab94-02815c1ae551.png)
How can i fix it? Thanks

**Comment by DJelly4K** [comment]
Plugin version: 0.8.1-Snapshot (Jenkins)

**Comment by A248** [comment]
This error message suggests there is *another issue* related to creating the database tables.

Can you use a new database, or wipe the libertybans tables in the database you're using, and try again? Let me know what error you receive **the first time**.

This error message, the one shown here, will show up the second time and the third time – I need your help to report the first error you receive when using LibertyBans on a fresh database.

**Comment by A248** [comment]
You need to grant proper permissions to the database user. This is an issue with your database configuration and not LibertyBans.

I don't how you set up your database user. If a host did it for you, that host misconfigured your database and you should raise a ticket with them. If you created the user yourself and you're familiar with SQL, the database user needs the `CREATE VIEW` privilege.
