### ISSUE TITLE
Cannot use Java 8

### ISSUE THREAD

**Issue by uIIIastic** [A248/LibertyBans#70]
My plugin is not translated into a folder. It stupidly stays in the heat of the jar and the plugin itself does not work. What do i do?

**Comment by uIIIastic** [comment]
[latest.log](https://github.com/A248/LibertyBans/files/7206310/latest.log)

**Comment by A248** [comment]
You need to use Java 11 or a newer Java version. Contact your host and ask them to upgrade to Java 11 or later.

I recommend using Java 17 if your software is compatible.

**Comment by A248** [comment]
This message tells you to use Java 11:
> [19:20:01] [Server thread/ERROR]: [LibertyBans] Your version of Java (Detected Java 8) is outdated. Please upgrade to at least JDK 11 in order for LibertyBans to work properly. To install Java 11 or any later version, see https://adoptopenjdk.net/

I'll make this message more obvious since it is easy to miss.
