### ISSUE TITLE
Intelligent Bans

### ISSUE THREAD

**Issue by BlueTree242** [A248/LibertyBans#81]
So... The things ill say must be optionable

- Player is already ip-banned without /ipban
- Player joins same name with diffrent ip the ip is ip banned too
- Player joins with same ip with another name the name is also banned and everything is applied on them

Result:
Making it harder to bypass a ban

This idea was in my mind for long time even i thought of making my own plugin for it but i am busy and can't do it myself. If you add this (OPTIONAL) the plugin will be special.

Also another suggestion.. Ban exempts.. But works with luckperms weight.. Another point for Libertybans!!

**Comment by A248** [comment]
We already have advanced means for detecting and enforcing bans on IP addresses. However, we do not yet have the ability to make a punishment which applies to both a UUID and IP address.

Note that LibertyBans does *not* ban by name, but rather UUID or IP address.

For IP address punishments, there is an option called address-strictness which does the following:
* Lenient address enforcement prevents a player from joining if their current address matches the banned address
* Normal address enforcement prevents a player from joining if any of their past addresses match the banned address
* Strict address enforcement prevents a player from joining if one of the following is true:
  * Any of their past addresses match the banned address
  * Any player exists, who has joined with an address in common with the player now joining, and one of whose past addresses matches the banned address

> Player joins with same ip with another name the name is also banned and everything is applied on them

If you use an IP address-based punishment, both the `NORMAL` and `STRICT` address enforcement levels cover this case.

> Player joins same name with diffrent ip the ip is ip banned too

If you use a UUID-based punishment, players joining with the same UUID will remain banned.

A current limitation is that punishments cannot be both UUID-based and IP-based. This is planned to be implemented and is covered by [Issue 73](https://github.com/A248/LibertyBans/issues/73)

> Player is already ip-banned without /ipban

This feature we don't yet have. This is planned to be implemented and is covered by [Issue 73](https://github.com/A248/LibertyBans/issues/73)

### My Conclusion

To fulfill this feature request, LibertyBans needs to resolve [Issue 73](https://github.com/A248/LibertyBans/issues/73) which will satisfy all the features you've mentioned.

**Comment by A248** [comment]
Closing in favor of #73
