### ISSUE TITLE
[Feature Request]: /checkpunish

### ISSUE THREAD

**Issue by craciu25yt** [A248/LibertyBans#93]
### I have confirmed that ...

- [X] There is no duplicate feature request.

### Description

Add one /checkpunish and you can see using the ban Id.
Ex: /checkpunish 3
     /checkp 5
     / checkpunishment 10

**Comment by BlueTree242** [comment]
Why would you need this

**Comment by craciu25yt** [comment]
For make util the punish id (%ID% - punishment ID number) and because I wanna make appeal system with the number because is more easy than type the name of someone called PepeElGringx035_TW_YT_patata

**Comment by pwnker** [comment]
Yeah this would also solve #94

**Comment by pwnker** [comment]
Although you can see current bans with ids using `/banlist`

**Comment by A248** [comment]
The `/libertybans checkpunish` command is heretofore implemented by the checkpunish addon: https://ci.hahota.net/job/LibertyBans/

Using the config.yml you can add "checkpunish" to the list of command aliases to enable the `/checkpunish` command.
