### ISSUE TITLE
[Feature Request]: Show IP bans in history command when searching a username

### ISSUE THREAD

**Issue by pwnker** [A248/LibertyBans#94]
### Description

Currently when you run `/history <username>` IP bans for the username are not shown in the list. This makes appeals difficult as you cannot determine which currently banned IP belongs to the user in question. The history command should be updated to display both bans and IP bans for a user or IP.

**Comment by A248** [comment]
Based on how you are using IP-bans -- as the default punishment for users -- what I believe you want is composite victim feature: https://github.com/A248/LibertyBans/issues/73 .

IP-Bans are not user-specific. I suppose it would be possible to show *applicable* punishments in /history, though that would change the meaning of the command; which would either preclude use of the form `/history <IP address>` or make the command behave differently for usernames and IP addresses.

I'm going to close this in favor of the linked issue, which I think is much more suitable to your use-case.
